apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-sample
  annotations:
    github.com/project-slug: tinmegali-connected/backstage-sample
spec:
  type: other
  lifecycle: unknown
  owner: guests
